-d D:\Gowin_code\hdmi_standard_readfromfifo\impl\gwsynthesis\hdmi_standard.vg
-p GW2A-18C-PBGA256-8
-pn GW2A-LV18PG256C8/I7
-cst D:\Gowin_code\hdmi_standard_readfromfifo\src\hdmi_standard.cst
-cfg D:\Gowin_code\hdmi_standard_readfromfifo\impl\pnr\device.cfg
-sdc D:\Gowin_code\hdmi_standard_readfromfifo\src\hdmi_standard.sdc
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
