-d C:\Users\YJQ\Desktop\sd_read_modelpara_new\impl\gwsynthesis\sd_read_modelpara_new.vg
-p GW2A-18C-PBGA256-8
-pn GW2A-LV18PG256C8/I7
-cst C:\Users\YJQ\Desktop\sd_read_modelpara_new\src\sd_read_model_para_new.cst
-cfg C:\Users\YJQ\Desktop\sd_read_modelpara_new\impl\pnr\device.cfg
-sdc C:\Users\YJQ\Desktop\sd_read_modelpara_new\src\sd_read_model_para_new.sdc
-gao_crc 0010100011010000
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
-rtl_gao
